apiVersion: v1
data:
    KAGENT_LLM_KEY: ENC[AES256_GCM,data:i135XL33b49uDDO24T6AAcJtvoitjlbGjB7gfeGxIZrdiuIYBX280I58iTdvwIxyYhdcjhh9np6hiYlejfUkTZavNGi+wQ/a3Hn8e45Ep8OyFBRD4i/YxQ==,iv:qUGMqs7epaq2q78b7zp7zSPlShy8gxxvGBtdN/F8muU=,tag:0UmRgNwDmhZQmYlPx4929g==,type:str]
kind: Secret
metadata:
    name: agentgateway-llm-secrets
    namespace: agentgateway-system
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByS0hGdTJ2eFN6OTgwd3M3
            c2w5TFRTWVlpT25CMjlyNk5rdndaV3pSWW1zCmFyVjE5N09vMHFzRVFPWWl4Wmsx
            RFdWN0pQK3Z1SWxsNkNwdW1CQnJTVVUKLS0tIHBLQy9ZUWJDK1V3MFJuZWdMQU8v
            VXFNR3JJbFF6NVR2UFdGS2I1OXpmeUEKzlMoNMck6kY+LXWDidy7/QAChj47jR2/
            GthULgCwhyv8c8u5Vl/MmkbRjD2PMdelY9OqybtdQ8abXbKySp2fSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cc2g2aw4rd538g4vw8m9qy6tytkcsyzmxxgsdkvph7evdn44t37qlrdncu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T17:34:16Z"
    mac: ENC[AES256_GCM,data:VVVYiNnd5xICstryiaKykYZ9kU+Ws3cDeyI5CuLeZZRHTcY3/ONARftd3EhaibbJNMBdegnMrkh3OXJANpareQ2A/Gw7gj6UHxQCFSVHe1wwLU+H7cq1GmwXU68dR24OAoFF+ih1Apk0Qo7+nqFVr7dYlpxmPdvmkTlpBNskasc=,iv:yAkkHuhbLDBk00ZqCjs3sIVdjSuzLU/L5Ial12ezR2s=,tag:JDpXllWo57cl/t5CZFGrMg==,type:str]
    version: 3.13.3
