apiVersion: v1
data:
    OPENAI_API_KEY: ENC[AES256_GCM,data:E/J2F9ZvO+ULOwGJLFUYTrDK8Fabvbn3mbvlwpXMvFBjKVAj5iZIlu3GMyD87i00zLsWCC0tGfcDOCp655F6IKaW51h3HlhfVVsqUteKL2FZ2b9XXHOMLQ==,iv:3vtkF7FC+10my+lRBZ5EMNbNrVh/slmwC7GOwc6YPEw=,tag:1SK6jmbgubWgwNgNEfcxcA==,type:str]
kind: Secret
metadata:
    name: kagent-llm-key
    namespace: kagent
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRcTZlTVU3dHE0QzFrcFhq
            OWM4aXhZZ1c5emJtNDRQdVFJbUJnQ1lTdjBNCkpKVDZMYmdTVHFNQlQ4SEZGUTZT
            VzFQMjkvazRXZlpmMHRiaisxWnlPaW8KLS0tIGcydFViRlNHd082aElmamZtWlBY
            UnJQS1grKzFjT1pGbzZwWGUzdTZmM28KX3l20UTsU/HIOyWaaZ2cY279w4qnkqZI
            QbvXSKdo31kFUdC/vgM/B3hSWlGQIxplwoitkpEfh5/rq+W/e8JxiQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cc2g2aw4rd538g4vw8m9qy6tytkcsyzmxxgsdkvph7evdn44t37qlrdncu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T17:34:16Z"
    mac: ENC[AES256_GCM,data:bM4wkklWJVqyi9yRWxtcU2aQruJ7P4GGrMsbY1fwAIFSqSXacvG/X//pVplQx20+NbW+pXLCdvzYHJ0bpfm28TRU+YxssW9WUFlykQ0XUu2ueNdSwyoIAsCE/9c7QVJo0WQENDuC1fVQw+azqtv0UQO3/KXN98q4bolF3HKEvKs=,iv:SYa/OsyKTKZP28zi/DJhFdU+UPmXqAgRu28LKmtBFEk=,tag:UrxnUEObyaasrAa2TZ0EXQ==,type:str]
    version: 3.13.3
