apiVersion: v1
data:
    token: ENC[AES256_GCM,data:0UwkTJy1do6xRwOTsZ4rVmrZAwNjiyo35CKcWzU+AnnwLItt6GYugfE2BdL8mp1ekx/Kuj0p1gR+o5hAW8IGv/vSWEb6urM7pij5pu8d8VNxoYcBJrWlyw==,iv:3zLqGanHAqEBuD/GspDwGOUOfPnT2XV2fJM91psdXIo=,tag:6ewdJCS1rjZJ41Bv1SSAzw==,type:str]
kind: Secret
metadata:
    name: otel-ingest-token
    namespace: otel-ingest
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSTNpRXAzMTNXOHBvMlp6
            MVBkY0JMNU5oVzdVd1JDVm5VMHpMcDgwaVZFCnI3RXFZdEFhQU44N0ZBcmE1Y3BJ
            Z2hJY0w2bUsxZkRGWjdKa1RsSDd6ZEEKLS0tIE4weERFUXYvRHV4NDBsRWQ0aUI5
            TGNhaVI2UFJTZFNVRWJmaVdlUFQ3Q2MK6YUaAVI547DtKrmUPZijkf7vMXdS7HAB
            DXG8iLMeX2jDRudgazySIfMgNOsOe37amPkFESRTDHlPis6y9GiLUA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cc2g2aw4rd538g4vw8m9qy6tytkcsyzmxxgsdkvph7evdn44t37qlrdncu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T20:06:44Z"
    mac: ENC[AES256_GCM,data:ujMW2uRiaqNa+IqK9m/2rS6/pwQl3x9dpknw7OzvMDJh9TzOkfDUU+WvDk4P1qtDXTuEnVCCb1/p5y7jZH5UtZknfWHUyVOy1/GmYp+XG5u68eLOgpPgCCfx/8AzsNr64j/TpvULacaqdmrYhPC0JKH26X6Expw8jdxKBiuHjvU=,iv:/0EQ1oVc/bnKisneoHE6huU8jNBnNBt/DYIvP1relEQ=,tag:1Ez+13dkLNbd3dxEOF4o9Q==,type:str]
    version: 3.13.3
