apiVersion: v1
data:
    token: ENC[AES256_GCM,data:MCGUicoNQMAfI91VYfuPd82zrqmkAmE/Wr9xCt9czRwCIn+GJJW+8ahCGp2xJswsqewSiKlpZW2a/hOTqsNtGqXgqOgf0IUGIPs5FcNygbERL4j8+V/m9A==,iv:F0yjmWjfzTn24ImBdm4M+YKjnlylGDZw7eFMfXL4Foo=,tag:R+NwvxdAYvx9ZWlfzsqu7Q==,type:str]
kind: Secret
metadata:
    name: xray-memory-auth
    namespace: xray-memory
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1T1J4UDcraUNHOU1xQjJO
            VThjVlUwN2RiVGlEU1Z4Z0FwdXlzL1dzT0FRCmN6OXhrbU5sYkM0MWxYL2ZNYXd0
            YlRrcUliTzNUdWlROEhKR1QyM3h0czAKLS0tIC9lWU1tck1xdWJHZWFSa093SkFk
            SXR6bDVTcWJ0N3RwNENVVC81T0NHMkEKbySqWKB5XhhNC2PhMIiZ9deFYTLC17ci
            2Q9d4kxxc6fNX2dY6n/VbU1kA/NG5tPMCrU3lYwckfsTgiZWXFWEOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cc2g2aw4rd538g4vw8m9qy6tytkcsyzmxxgsdkvph7evdn44t37qlrdncu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T17:12:04Z"
    mac: ENC[AES256_GCM,data:6zDJVwy+aGHBdoCJ+mcHXY4Spz3rwWfttSZx03t+bf7/GmchpJfx1sE/4CVxftFjrjK4wBwZ8tOCLPpYB3c214qB0K25KGPMRvKMMzs/EmG3GbXb3qR4f3gKjmQbJjRT6rYIxCtNe7j+elUI0zK+5D/WjuEmWF02QcDb3K6XwhA=,iv:Ey4BPl5Y/ma13wEE+YpC2aMTRpo8Yy9BQVJ/FE04z2s=,tag:R5UcHaGBgJ1xBkO2axsJbQ==,type:str]
    version: 3.13.3
