apiVersion: v1
data:
    identity: ENC[AES256_GCM,data:n/VORxtWKwLBTISb6HVW3VxxYZ2RX72RkL4WBpQO/mkiuGeqlxCYdtc1nrlu/CHjNUlTabCzvMZAQTtaUTNQJs5TS92aHDSJ3aiJB1d9QnUoPTtNo/7Lnh3xpX2aM7L8qESHLjixcckpQ7LrMqOoG3+IpcBhA+Wdl8fs0VyMlOsohdalfAKTkbAtwrQBo9Ml9KtTmgmlrNuCFkKcMNqzASQSqF5sYBE3ydLbx5PxFpFhC5veLthV1QZcXLBVf6oDnDZw6IBgseOS6AgCkDlmzVESjFXE93Femkiad3O8phnpt4cvq3NZ6wZ3KrNJJ2qSPHXzb1cNu2AJSPXn,iv:8hzz5UaIaNhtBEi2LnVDluHdexh8IKCG/pFD8hBOoC0=,tag:F8/pXdHlsA8EQc4jNMUyLw==,type:str]
kind: Secret
metadata:
    name: xray-memory-snapshot-key
    namespace: xray-memory
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Mi81eFljdEZZeXN1TjdI
            eG4wUWFXWm5tcmljM2xaZEE1MnNtdFhlRXpzCnQycUlQbWJ4Z1ZIalBsOWQ4NG9F
            cEZUdzVGc2Uybkl5WXhPMGhkMnNsdHMKLS0tIEZsVVBrNU43T1JVL1grb3hxV2t4
            U2s5eDFTUHdlV0xuU0VmV3gvZnJ4K2MKlIkmfUl7C5772l8jWqw+ku18FvNP5xUM
            temWYqUuWD23ewbc3jR5nU7c6L+DpqzGtv+BhV1qZ2SIhEV53kXodg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cc2g2aw4rd538g4vw8m9qy6tytkcsyzmxxgsdkvph7evdn44t37qlrdncu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T17:12:04Z"
    mac: ENC[AES256_GCM,data:5DnkC7nM0vlnEAJLUj1ZKTrQm+u0ujB8UGcDuwlXJJLqaYiXfddMkuaIVpXPU65v9lLTn4IFN1sieq+7ONgeuH7zOsPqS1vCV0E4IZaHj7cUOD7W6TScMsMv9CONco/eVMHPSQhQV7JgQZIi0hv9do0JXd0kzZki2v+cErKz/HY=,iv:EsHmjNDuoIqJ7fa8CtzWl9mmrbk8VPLkhct4c16Pv8g=,tag:7pgSCNEzbaNM/bJaMPfMfw==,type:str]
    version: 3.13.3
