apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - agentgateway.yaml
  - agentgateway-llm.yaml
  - agentregistry.yaml
  - agent-retrieval.yaml
  - kagent.yaml
  - llama-cpp-embeddings.yaml
  - llmd.yaml
  - mcp-servers.yaml
  - neo4j.yaml
  - ngrok-operator.yaml
  - opentelemetry-demo.yaml
  - phoenix.yaml
  - qdrant.yaml
  - triage.yaml
  - triage-agent.yaml
  - triage-core.yaml
  - xray-memory.yaml
