apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secrets
  - agentgateway.yaml
  - agentgateway-llm.yaml
  - agentregistry.yaml
  - agent-retrieval.yaml
  - kagent.yaml
  - llama-cpp-chat.yaml
  - llama-cpp-embeddings.yaml
  - llmd.yaml
  - mcp-servers.yaml
  - mlflow.yaml
  - mlflow-otel-collector.yaml
  - neo4j.yaml
  - opentelemetry-demo.yaml
  - phoenix.yaml
  - qdrant.yaml
  - xray-memory.yaml
